name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install flake8 pytest

      # Step 4: Linting
      - name: Linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Testing
      - name: Testing
        run: pytest tests/

      # Step 6: Build and Run Docker
      - name: Build and Run Docker
        run: |
          docker build -t flaskapp:latest .
          docker run -d --name flaskapp -p 5000:5000 flaskapp
          docker ps
          docker logs -f flaskapp