name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install -r .github/workflows/requirements.txt
          python -m pip install flake8 pytest

      - name: Linting
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Testing
        run: pytest tests/

      - name: Build and Run Docker
        run: |
          docker build -t iris-model .
          docker run -p 5000:5000 iris-model
          docker run -p 8080:5000 iris-model          